In [1]:
pip install contractions

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.5/104.5 KB 3.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.5/287.5 KB 12.6 MB/s eta 0:00:00


In [2]:
pip install unidecode

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.9/235.9 KB 4.5 MB/s eta 0:00:00


In [3]:
pip install autocorrect

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 622.8/622.8 KB 12.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for autocorrect: filename=autocorrect-2.6.1-py3-none-any.whl size=622381 sha256=b3bd3cb17f03a9eb01b3cfa4cf461e4d5d496ccb28d6e546cc03bb7d260b9016
  Stored in directory: /root/.cache/pip/wheels/72/b8/3b/a90246d13090e85394a8a44b78c8abf577c0766f29d6543c75
Successfully built autocorrect


In [19]:
pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer,LancasterStemmer
from nltk.corpus import stopwords
from string import punctuation
import contractions
from unidecode import unidecode
from autocorrect import Speller

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split


In [101]:
# data=pd.read_csv('Train.csv',error_bad_lines=False)
# data

In [42]:
data=pd.read_csv('Train.csv',on_bad_lines='skip',engine='python')
data

text  label
0      I grew up (b. 1965) watching and loving the Th...      0
1      When I put this movie in my DVD player, and sa...      0
2      Why do people who do not know what a particula...      0
3      Even though I have great interest in Biblical ...      0
4      Im a die hard Dads Army fan and nothing will e...      1
...                                                  ...    ...
39995  "Western Union" is something of a forgotten cl...      1
39996  This movie is an incredible piece of work. It ...      1
39997  My wife and I watched this movie because we pl...      0
39998  When I first watched Flatliners, I was amazed....      1
39999  Why would this film be so good, but only gross...      1

[40000 rows x 2 columns]

In [43]:
data['text'][0]

'I grew up (b. 1965) watching and loving the Thunderbirds. All my mates at school watched. We played "Thunderbirds" before school, during lunch and after school. We all wanted to be Virgil or Scott. No one wanted to be Alan. Counting down from 5 became an art form. I took my children to see the movie hoping they would get a glimpse of what I loved as a child. How bitterly disappointing. The only high point was the snappy theme tune. Not that it could compare with the original score of the Thunderbirds. Thankfully early Saturday mornings one television channel still plays reruns of the series Gerry Anderson and his wife created. Jonatha Frakes should hand in his directors chair, his version was completely hopeless. A waste of film. Utter rubbish. A CGI remake may be acceptable but replacing marionettes with Homo sapiens subsp. sapiens was a huge error of judgment.'

In [44]:
data['label'][0]

0

In [45]:
#Preprocessing
#1. remove spaces and newlines and tabs
def remove_spaces(data):
  clean_text=data.replace('\\n',' ').replace('\t',' ').replace('\\',' ')
  return clean_text

In [46]:
#2. contraction mapping 
def expand_text(data):
  expand_text=contractions.fix(data)
  return expand_text

In [47]:
#3. Handelling accented characters
def handling_accented(data):
  fixed_text=unidecode(data)
  return fixed_text

In [48]:
#4. cleaning 
nltk.download('stopwords')
stopword_list=stopwords.words('english')
stopword_list.remove('no')
stopword_list.remove('nor')
stopword_list.remove('not')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [49]:
#5. tokenization,punctuation,stopword,normalization
def clean_data(data):
  tokens=word_tokenize(data)
  clean_text = [word.lower() for word in tokens if (word not in punctuation) and (word.lower() not in stopword_list) and (len(word)>2) and (word.isalpha())]
  return clean_text


In [50]:
#6.autocorrect
def autocorrection(data):
  spell=Speller(lang='en')
  corrected_text=spell(data)
  return corrected_text

In [51]:
#7.lemmatization
def lemmatization(data):
  lemmatizer=WordNetLemmatizer()
  final_data=[]
  for word in data:
    lemmatized_word=lemmatizer.lemmatize(word)
    final_data.append(lemmatized_word)
  return ' '.join(final_data)

In [52]:
#7.stemming
def stemming(data):
  stemming=LancasterStemmer()
  final_data=[]
  for word in data:
    stemming_word=stemming.stem(word)
    final_data.append(stemming_word)
  return ' '.join(final_data)

In [100]:
# count vectorizer
# tfidf  
# [w1 w2 w3]
# 'w1 w2 w3'

In [54]:
# Data Leakage
x_train,x_test,y_train,y_test=train_test_split(data.text,data.label,test_size=0.25,random_state=42)

In [55]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [56]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [57]:
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [58]:
clean_text_train = x_train.apply(remove_spaces)
clean_text_test = x_test.apply(remove_spaces)

clean_text_train = clean_text_train.apply(expand_text)
clean_text_test = clean_text_test.apply(expand_text)

clean_text_train = clean_text_train.apply(handling_accented)
clean_text_test = clean_text_test.apply(handling_accented)

clean_text_train = clean_text_train.apply(clean_data)
clean_text_test = clean_text_test.apply(clean_data)

clean_text_train = clean_text_train.apply(lemmatization)
clean_text_test = clean_text_test.apply(lemmatization)

# clean_text_train = clean_text_train.apply(stemming)
# clean_text_test = clean_text_test.apply(stemming)



In [102]:
# # parameters of count vectorizer, TF-IDF
# max_df >> by_default >> 1.0 >> 100%
# max_df = 1.0 >> 
# max_df = 0.95 >> 95% 

# 100 documents >>

# min_df >> by_default >> 1 >> single document
# min_df = 1 >> 
# min_df = 15 

# max_features >> 1000

# stopword = 'english'

# lower_case = True

In [59]:
clean_text_train

26898    fifth grade language art teacher read book stu...
27635    low budget brit pop melodrama focus girl want ...
3036     well watched movie little year ago pulled dust...
5604     would almost give however confusing part well ...
36111    full length feature film world bridge found fi...
                               ...                        
6265     movie one worst movie ever seen life waste tim...
11284    movie inspiring anyone tough jam whether finan...
38158    east side story documentary musical comedy sta...
860      one boot one point doctor assistant refers wor...
15795    movie horrible lighting terrible camera moveme...
Name: text, Length: 30000, dtype: object

In [60]:
clean_text_test

32823    central theme movie seems confusion relationsh...
16298    excellent example cowboy noir called unemploye...
28505    ending made heart jump throat proceeded leave ...
6689     chosen one appreciate quality story character ...
26893    really funny film especially second third four...
                               ...                        
29415    film came gift offering blue unlike reviewer p...
11359    first started watching movie looking kind subt...
575      big mark music neil young glowing praise film ...
17398    watching lady ermine wondering betty grable pr...
4189     crappy miserably acted movie based sublimated ...
Name: text, Length: 10000, dtype: object

In [74]:
# count vectorizer
count=CountVectorizer(max_df=0.95,max_features=1000)
count_val_train=count.fit_transform(clean_text_train)
count_val_test=count.fit_transform(clean_text_test)

In [75]:
count_val_train

<30000x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 1617713 stored elements in Compressed Sparse Row format>

In [76]:
count_val_train.A

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [77]:
count_val_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [78]:
count_val_test

<10000x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 547574 stored elements in Compressed Sparse Row format>

In [79]:
count_val_test.A

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [80]:
count.get_feature_names()

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['ability',
 'able',
 'absolutely',
 'accent',
 'across',
 'act',
 'acted',
 'acting',
 'action',
 'actor',
 'actress',
 'actual',
 'actually',
 'adaptation',
 'add',
 'admit',
 'adult',
 'adventure',
 'affair',
 'age',
 'agent',
 'ago',
 'agree',
 'air',
 'alien',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'amazing',
 'america',
 'american',
 'among',
 'amount',
 'amusing',
 'animal',
 'animated',
 'animation',
 'annoying',
 'another',
 'answer',
 'anyone',
 'anything',
 'anyway',
 'apart',
 'apparently',
 'appear',
 'appearance',
 'appears',
 'appreciate',
 'army',
 'around',
 'art',
 'aside',
 'ask',
 'aspect',
 'atmosphere',
 'attempt',
 'attention',
 'audience',
 'average',
 'avoid',
 'award',
 'away',
 'awesome',
 'awful',
 'baby',
 'back',
 'background',
 'bad',
 'badly',
 'band',
 'based',
 'basic',
 'basically',
 'battle',
 'beat',
 'beautiful',
 'beauty',
 'became',
 'become',
 'becomes',
 'bed',
 'begin',
 'beginning',
 'behind',
 'believabl

In [81]:
len(count.get_feature_names())

1000

In [82]:
pd.DataFrame(count_val_train.A,columns=count.get_feature_names())

ability  able  absolutely  accent  across  act  acted  acting  action  \
0            0     0           0       0       0    0      0       2       0   
1            0     0           0       0       0    0      0       0       0   
2            0     0           0       0       0    0      0       0       0   
3            0     0           0       1       0    0      0       0       0   
4            0     0           2       0       0    0      0       0       0   
...        ...   ...         ...     ...     ...  ...    ...     ...     ...   
29995        0     0           0       0       0    1      0       1       0   
29996        0     0           0       0       0    0      0       0       0   
29997        0     0           0       0       0    0      0       0       0   
29998        0     0           0       0       0    0      0       1       0   
29999        0     0           0       0       0    0      0       1       0   

       actor  ...  written  wrong  yeah  year  yes  yet  york  young  younger  \
0          0  ...        0      0     0     0    0    0     0      0        0   
1          0  ...        0      0     0     0    0    0     0      0        0   
2          0  ...        0      0     0     1    0    0     0      0        0   
3          0  ...        0      0     0     0    0    0     0      0        0   
4          0  ...        0      0     0     0    0    0     0      0        0   
...      ...  ...      ...    ...   ...   ...  ...  ...   ...    ...      ...   
29995      0  ...        0      0     0     0    0    0     0      0        0   
29996      0  ...        0      0     0     0    0    0     0      0        0   
29997      0  ...        0      0     0     1    0    0     0      0        0   
29998      0  ...        1      0     0     0    0    0     0      0        0   
29999      0  ...        0      1     0     1    0    0     0      0        0   

       zombie  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
29995       0  
29996       0  
29997       0  
29998       0  
29999       0  

[30000 rows x 1000 columns]

In [95]:
#Build Model
count_mnb = MultinomialNB()
count_mnb.fit(count_val_train.A,y_train)

MultinomialNB()

In [96]:
# Model Evaluation
predict_count = count_mnb.predict(count_val_test.A)
accuracy_count = accuracy_score(y_test,predict_count)*100
accuracy_count

57.68

In [85]:
tfidf = TfidfVectorizer(max_df=0.95,max_features=1000)
tfidf_train = tfidf.fit_transform(clean_text_train)
tfidf_test = tfidf.transform(clean_text_test)

In [86]:
tfidf_train.A

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [87]:
tfidf_train.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [88]:
tfidf_test.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.12275876,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.06692787, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.09879821, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [89]:
tfidf.get_feature_names()

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['ability',
 'able',
 'absolutely',
 'accent',
 'across',
 'act',
 'acted',
 'acting',
 'action',
 'actor',
 'actress',
 'actual',
 'actually',
 'adaptation',
 'add',
 'admit',
 'adult',
 'adventure',
 'age',
 'ago',
 'agree',
 'air',
 'alien',
 'alive',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'amazing',
 'america',
 'american',
 'among',
 'amount',
 'animal',
 'animation',
 'annoying',
 'another',
 'answer',
 'anyone',
 'anything',
 'anyway',
 'apart',
 'apparently',
 'appeal',
 'appear',
 'appearance',
 'appears',
 'appreciate',
 'army',
 'around',
 'art',
 'aside',
 'ask',
 'aspect',
 'atmosphere',
 'attack',
 'attempt',
 'attention',
 'audience',
 'average',
 'avoid',
 'award',
 'away',
 'awesome',
 'awful',
 'baby',
 'back',
 'background',
 'bad',
 'badly',
 'band',
 'barely',
 'based',
 'basic',
 'basically',
 'battle',
 'beautiful',
 'beauty',
 'became',
 'become',
 'becomes',
 'begin',
 'beginning',
 'behind',
 'belief',
 'believable',
 'bel

In [90]:
len(tfidf.get_feature_names())

1000

In [92]:
pd.DataFrame(tfidf_train.A,columns=tfidf.get_feature_names())

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


ability  able  absolutely    accent  across       act  acted    acting  \
0          0.0   0.0    0.000000  0.000000     0.0  0.000000    0.0  0.182468   
1          0.0   0.0    0.000000  0.000000     0.0  0.000000    0.0  0.000000   
2          0.0   0.0    0.000000  0.000000     0.0  0.000000    0.0  0.000000   
3          0.0   0.0    0.000000  0.137926     0.0  0.000000    0.0  0.000000   
4          0.0   0.0    0.321531  0.000000     0.0  0.000000    0.0  0.000000   
...        ...   ...         ...       ...     ...       ...    ...       ...   
29995      0.0   0.0    0.000000  0.000000     0.0  0.135608    0.0  0.088057   
29996      0.0   0.0    0.000000  0.000000     0.0  0.000000    0.0  0.000000   
29997      0.0   0.0    0.000000  0.000000     0.0  0.000000    0.0  0.000000   
29998      0.0   0.0    0.000000  0.000000     0.0  0.000000    0.0  0.050570   
29999      0.0   0.0    0.000000  0.000000     0.0  0.000000    0.0  0.097604   

       action  actor  ...    wrong     wrote  yeah      year  yes  yet  york  \
0         0.0    0.0  ...  0.00000  0.000000   0.0  0.000000  0.0  0.0   0.0   
1         0.0    0.0  ...  0.00000  0.000000   0.0  0.000000  0.0  0.0   0.0   
2         0.0    0.0  ...  0.00000  0.000000   0.0  0.055835  0.0  0.0   0.0   
3         0.0    0.0  ...  0.00000  0.000000   0.0  0.000000  0.0  0.0   0.0   
4         0.0    0.0  ...  0.00000  0.000000   0.0  0.000000  0.0  0.0   0.0   
...       ...    ...  ...      ...       ...   ...       ...  ...  ...   ...   
29995     0.0    0.0  ...  0.00000  0.000000   0.0  0.000000  0.0  0.0   0.0   
29996     0.0    0.0  ...  0.00000  0.000000   0.0  0.000000  0.0  0.0   0.0   
29997     0.0    0.0  ...  0.00000  0.000000   0.0  0.074142  0.0  0.0   0.0   
29998     0.0    0.0  ...  0.07508  0.000000   0.0  0.000000  0.0  0.0   0.0   
29999     0.0    0.0  ...  0.00000  0.189091   0.0  0.102630  0.0  0.0   0.0   

       young  younger  zombie  
0        0.0      0.0     0.0  
1        0.0      0.0     0.0  
2        0.0      0.0     0.0  
3        0.0      0.0     0.0  
4        0.0      0.0     0.0  
...      ...      ...     ...  
29995    0.0      0.0     0.0  
29996    0.0      0.0     0.0  
29997    0.0      0.0     0.0  
29998    0.0      0.0     0.0  
29999    0.0      0.0     0.0  

[30000 rows x 1000 columns]

In [93]:
# Model Building
tfidf_mnb=MultinomialNB()
tfidf_mnb.fit(tfidf_train.A,y_train)

MultinomialNB()

In [94]:
#Model Training
predict_tfidf=tfidf_mnb.predict(tfidf_test.A)
accuracy_tfidf = accuracy_score(y_test,predict_tfidf)*100
accuracy_tfidf

83.71

In [ ]:
# downword part is not sentimental analysis its new topic of EDA

In [97]:
from nltk.util import ngrams

In [98]:
# [w1 w2 w3]
def splitting_dataframe(data):
  tokens=data.split()
  return tokens

data=clean_text_test.apply(splitting_dataframe)

def ngram_list(data,ngram_range):
  ngram=ngrams(data,ngram_range) # zip file
  ngram_list1=[]
  for ngram1 in ngram: #opening the zip file
    ngram_list1.append(' '.join(ngram1))
  return ngram_list1



In [99]:
# ngram_range >>1 >>unigram
# 2 >>bigram
# 3 >>Trigram

In [104]:
unigrams=data.apply(lambda x : ngram_list(x,1)) # x >> single revies
unigrams

32823    [central, theme, movie, seems, confusion, rela...
16298    [excellent, example, cowboy, noir, called, une...
28505    [ending, made, heart, jump, throat, proceeded,...
6689     [chosen, one, appreciate, quality, story, char...
26893    [really, funny, film, especially, second, thir...
                               ...                        
29415    [film, came, gift, offering, blue, unlike, rev...
11359    [first, started, watching, movie, looking, kin...
575      [big, mark, music, neil, young, glowing, prais...
17398    [watching, lady, ermine, wondering, betty, gra...
4189     [crappy, miserably, acted, movie, based, subli...
Name: text, Length: 10000, dtype: object

In [105]:
bigrams = data.apply(lambda x : ngram_list(x,2)) # x >> two words review
bigrams

32823    [central theme, theme movie, movie seems, seem...
16298    [excellent example, example cowboy, cowboy noi...
28505    [ending made, made heart, heart jump, jump thr...
6689     [chosen one, one appreciate, appreciate qualit...
26893    [really funny, funny film, film especially, es...
                               ...                        
29415    [film came, came gift, gift offering, offering...
11359    [first started, started watching, watching mov...
575      [big mark, mark music, music neil, neil young,...
17398    [watching lady, lady ermine, ermine wondering,...
4189     [crappy miserably, miserably acted, acted movi...
Name: text, Length: 10000, dtype: object

In [106]:
trigrams = data.apply(lambda x : ngram_list(x,3)) # x >> three word review
trigrams

32823    [central theme movie, theme movie seems, movie...
16298    [excellent example cowboy, example cowboy noir...
28505    [ending made heart, made heart jump, heart jum...
6689     [chosen one appreciate, one appreciate quality...
26893    [really funny film, funny film especially, fil...
                               ...                        
29415    [film came gift, came gift offering, gift offe...
11359    [first started watching, started watching movi...
575      [big mark music, mark music neil, music neil y...
17398    [watching lady ermine, lady ermine wondering, ...
4189     [crappy miserably acted, miserably acted movie...
Name: text, Length: 10000, dtype: object